 ---
 - hosts: 127.0.0.1
   connection: local
   tasks:
   - name: "update"
     apt:
      upgrade: true
     become: true

   - name: "install sshpass"
     #command: apt-get install sshpass
     apt:
       name: sshpass
       state: latest
     become: yes

     - name: “generate sshkey”
     - openssh_keypair:
          path: /home/azureadmin/.ssh/id_rsa
          size: 4096
     become: yes
  


    

   
 
  
    
