--- 
- 
  become: true
  file: 
    group: www-data
    mode: 493
    owner: www-data
    path: /var/www/html
    state: directory
  name: "Create webroot"
- 
  name: "Check if Moodle archive exists"
  register: moodle_path
  stat: path=/tmp/moodle-3.6.tgz
- 
  get_url: "dest=/tmp/ url=https://download.moodle.org/stable36/moodle-3.6.3.tgz"
  name: "Download Moodle archive"
  when: "(moodle_path.stat.exists == false)"
- 
  become: true
  name: "Extract moodle"
  unarchive: 
    copy: false
    dest: /tmp
    group: www-data
    owner: www-data
    src: /tmp/moodle-3.6.3.tgz

- 
  name: create a database
  command: mysql -h {{ dbservername | quote }} -u {{ dbusername | quote }} -p{{ dbpassword | quote }} -e "CREATE DATABASE moodledb CHARACTER SET utf8;"
  register: output
- debug: var=output.stdout_lines

- 
  name: grant user permission to database
  command: mysql -h {{ dbservername | quote }} -u {{ dbusername | quote }} -p{{ dbpassword | quote }} -e "GRANT ALL ON moodledb.* TO moodle IDENTIFIED BY 'Moodle@123';"
  register: outputpremission
- debug: var=outputpremission.stdout_lines

- name: Create a moodle data parent directory if it does not exist
  file:
    path: /tmp/lamp
    state: directory
    mode: '0777'
 
- name: Create a moodle data directory if it does not exist
  file:
    path: /tmp/lamp/moodledata
    state: directory
    mode: '0755'

- 
  become: true
  command: "mv /tmp/lamp/ /tmp/moodle/"
  name: "Move moodledata directory"  

- 
  become: true
  command: "mv /tmp/moodle /var/www/html/{{ hostname }}"
  name: "Move moodle install files"

- 
  name: Install moodle
  command: echo -e "cd /tmp; /usr/bin/php /var/www/html/{{ hostname }}/admin/cli/install.php --chmod=770 --lang=en_us --wwwroot="http"://"{{ domain_name | quote }}" --dataroot=/var/www/html/{{ hostname }}/lamp/moodledata --dbhost="{{ dbservername | quote }}" --dbname="moodledb" --dbuser="{{ dbusername | quote }}" --dbpass="{{ dbpassword | quote }}" --dbtype=mysqli --fullname='Moodle LMS' --shortname='Moodle' --adminuser=admin --adminpass="Moodle@123" --adminemail=admin@"{{ domain_name | quote }}" --non-interactive --agree-license --allow-unstable || true "
  command: cd /tmp; /usr/bin/php /tmp/moodle/admin/cli/install.php --chmod=770 --lang=en_us --wwwroot=http://{{ domain_name | quote }} --dataroot=/var/www/html/{{ hostname }}/lamp/moodledata --dbhost={{ dbservername | quote }} --dbname=moodledb --dbuser={{ dbusername | quote }} --dbpass={{ dbpassword | quote }} --dbtype=mysqli --fullname='Moodle LMS' --shortname='Moodle' --adminuser=admin --adminpass=Moodle@123 --adminemail=admin@{{ domain_name | quote }} --non-interactive --agree-license --allow-unstable || true
  become: true 
  
- 
  file: "path=/var/www/html/moodle owner=www-data group=www-data state=directory recurse=yes"
  name: "Change ownership of Moodle"
  
