
# tasks file for moodle

- name: Create webroot
  file:
    state: directory
    path: /var/www/html
    owner: root
    group: root
    mode: 0755
  become: yes
  
- name: Check if Moodle archive exists
  stat: path=/tmp/moodle-3.6.tgz
  register: moodle_path
  
- name: Download Moodle archive
  get_url: dest=/tmp/ url=https://download.moodle.org/stable36/moodle-3.6.3.tgz
  when: (moodle_path.stat.exists == false)

- name: Extract moodle
  unarchive:
    src: /tmp/moodle-3.6.3.tgz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  become: yes

- name: Move moodle install files
  command: mv /tmp/moodle /var/www/html/{{ hostname }}
  become: yes

- name: Fix ownership of Moodle
  file: path=/var/www/html/moodle owner=www-data group=www-data state=directory recurse=yes

- name: Create moodledata directory
  file: path=/var/moodledata owner=www-data group=www-data state=directory recurse=yes
  become: yes
