--- 
- 
  become: true
  file: 
    group: www-data
    mode: 493
    owner: www-data
    path: /var/www/html
    state: directory
  name: "Create webroot"
- 
  name: "Check if Moodle archive exists"
  register: moodle_path
  stat: path=/tmp/moodle-3.6.tgz
- 
  get_url: "dest=/tmp/ url=https://download.moodle.org/stable36/moodle-3.6.3.tgz"
  name: "Download Moodle archive"
  when: "(moodle_path.stat.exists == false)"
- 
  become: true
  name: "Extract moodle"
  unarchive: 
    copy: false
    dest: /tmp
    group: www-data
    owner: www-data
    src: /tmp/moodle-3.6.3.tgz
- 
  become: true
  command: "mv /tmp/moodle /var/www/html/{{ hostname }}"
  name: "Move moodle install files"
- 
  file: "path=/var/www/html/moodle owner=www-data group=www-data state=directory recurse=yes"
  name: "Fix ownership of Moodle"
- 
  become: true
  file: "path=/var/moodledata owner=www-data group=www-data state=directory recurse=yes"
  name: "Create moodledata directory"

- name: Add config.php
  template: "src=config.php dest=/var/www/html/{{ hostname }}/config.php"
  become: yes

- name: Update Moodle config file

lineinfile:
dest: "/var/www/html/{{ hostname }}/config.php"
description: "It will find regexp and replace line"
regexp: "{{ item.regexp }}"
line: "{{ item.line }}"
with_items:
- {'regexp': "define\\('db_name', '(.)+'\\);", 'line': "define('db_name', '{{db_name}}');"}
- {'regexp': "define\\('db_user', '(.)+'\\);", 'line': "define('db_user', '{{d_username}}');"}
- {'regexp': "define\\('db-password', '(.)+'\\);", 'line': "define('db_password', '{{db_password}}');"}
become: yes
