--- 
- 
  become: true
  file: 
    group: "{{default_permission}}"
    mode: 493
    owner: "{{default_permission}}"
    path: "{{webroot}}"
    state: directory
  name: "Create webroot"
- 
  name: "Check if Moodle archive exists"
  register: moodle_path
  stat: path="{{moodle_download_path}}-{{version}}.tgz"
- 
  get_url: "dest=/tmp/ url={{moodle_download_url}}-{{version}}.tgz"
  name: "Download Moodle archive"
  when: "(moodle_path.stat.exists == false)"
- 
  become: true
  name: "Extract moodle"
  unarchive: 
    copy: false
    dest: /tmp
    group: "{{default_permission}}"
    owner: "{{default_permission}}"
    src: "{{moodle_download_path}}-{{version}}.tgz"

- 
  name: create a database
  command: mysql -h {{dbservername}} -u {{dbusername}} -p{{dbpassword}} -e "CREATE DATABASE {{moodle_db_name}} CHARACTER SET utf8;"
  register: output
- debug: var=output.stdout_lines

- 
  name: grant user permission to database
  command: mysql -h {{dbservername}} -u {{dbusername}} -p{{dbpassword}} -e "GRANT ALL ON {{moodle_db_name}}.* TO moodle IDENTIFIED BY 'Moodle@123';"
  register: outputpremission
- debug: var=outputpremission.stdout_lines

- name: Create a moodle data parent directory if it does not exist
  become: true
  file:
    path: "{{moodle_data_dir}}/"
    state: directory
    mode: '0777'
    group: "{{default_permission}}"
    owner: "{{default_permission}}"

 
- name: Create a moodle data directory if it does not exist
  become: true
  file:
    path: "{{moodle_data_dir}}/moodledata/"
    state: directory
    mode: '0755'
    group: "{{default_permission}}"
    owner: "{{default_permission}}"    

#- 
#  become: true
#  command: "mv {{moodle_data_dir}}/ {{moodle_data_target_path}}/"
#  name: "Move moodledata directory"  
  
- 
  become: true
  command: "mv {{moodle_download_path}}/ {{webroot}}/{{ hostname }}/"
  name: "Move moodle install files"


# sudo -u www-data /usr/bin/php admin/cli/install.php --wwwroot=http://{{lbip}}/moodle --dataroot={{moodle_data_dir}}/moodledata--dbtype=mysqli --dbhost={{dbservername}} --dbname={{moodle_db_name}} --dbuser={{dbusername}}--dbpass={{dbpassword}} --fullname='Moodle LMS'--shortname='Moodle' —adminuser=admin --adminpass=Moodle@123 --non-interactive --agree-license
# echo -e "cd /tmp; /usr/bin/php {{webroot}}/{{hostname}}/admin/cli/install.php --chmod=770 --lang=en_us --wwwroot="http"://"{{lbip}}" --dataroot={{moodle_data_dir}}/moodledata --dbhost="{{dbservername}}" --dbname="{{moodle_db_name}}" --dbuser="{{dbusername}}" --dbpass="{{dbpassword}}" --dbtype=mysqli --fullname='Moodle LMS' --shortname='Moodle' --adminuser=admin --adminpass="Moodle@123" --adminemail=admin@"{{domain_name}}" --non-interactive --agree-license --allow-unstable || true "
- 
  name: Install moodle echo
  command: echo -e "-u www-data /usr/bin/php {{webroot}}/{{hostname}}/admin/cli/install.php --wwwroot=http://{{lbip}}/moodle --dataroot={{moodle_data_dir}}/moodledata --dbtype=mysqli --dbhost={{dbservername}} --dbname={{moodle_db_name}} --dbuser={{dbusername}} --dbpass={{dbpassword}} --fullname='Moodle LMS' --shortname='Moodle' —adminuser=admin --adminpass=Moodle@123 --non-interactive --agree-license"
  become: true 
  
- 
  name: Install moodle
  command: -u www-data /usr/bin/php {{webroot}}/{{hostname}}/admin/cli/install.php --wwwroot=http://{{lbip}}/moodle --dataroot={{moodle_data_dir}}/moodledata --dbtype=mysqli --dbhost={{dbservername}} --dbname={{moodle_db_name}} --dbuser={{dbusername}} --dbpass={{dbpassword}} --fullname='Moodle LMS' --shortname='Moodle' —adminuser=admin --adminpass=Moodle@123 --non-interactive --agree-license
  become: true 
  
- 
  file: "path={{webroot}}/moodle owner={{default_permission}} group={{default_permission}} state=directory recurse=yes"
  name: "Change ownership of Moodle"
