--- 
- 
  command: command ssh-keygen -q -t rsa -f /home/"{{user_name | quote }}"/.ssh -C "" -N ""
  args:
     creates: /home/{{user_name | quote }}/.ssh
  deligate_to: "127.0.0.1"
  name: "Generate RSA host key"
