--- 
-   name: Generate RSA host key
    local_action: command ssh-keygen -q -t rsa -f /home/{{user_name | quote }}/.ssh -C "" -N ""
    args:
      creates: /home/{{user_name | quote }}/.ssh
    
