- hosts: webservers

  tasks:
    - name: ssh key configuration
      command: sudo apt-get update
      command: sudo apt-get install sshpass
      command: sudo ssh-keygen -t rsa -N '' -f
      command:  echo "${{vm_password | quote }}" | sshpass ssh-copy-id -f -i /home/{{user_name | quote }}/.ssh/id_rsa.pub {{user_name | quote }}@"{{vm_ip | quote }}"

      
