- hosts: webservers

  tasks:
    - name: ssh key configuration
     local_action: command sudo apt-get update
     local_action: command sudo apt-get install sshpass
     local_action: command sudo ssh-keygen -t rsa -N '' -f /home/{{user_name | quote }}/.ssh/id_rsa <<< y
     local_action: command echo "${{vm_password | quote }}" | sshpass ssh-copy-id -f -i /home/{{user_name | quote }}/.ssh/id_rsa.pub {{user_name | quote }}@"{{vm_ip | quote }}"
     delegate_to: localhost
      
