--- 
- 
  local_action: command apt-get update
  name: "update"
  become: yes
- 
  local_action: command apt-get install sshpass
  name: "install sshpass"
  become: yes
- 
  local_action: command sudo ssh-keygen -t rsa -N '' -f /home/{{user_name | quote }}/.ssh/id_rsa <<< y
  name: "generate key"
  become: yes
  
- 
  local_action: command  echo "{{vm_password | quote }}" | sshpass ssh-copy-id -f -i /home/{{user_name | quote }}/.ssh/id_rsa.pub {{user_name | quote }}@"{{vm_ip | quote }}"
  name: "copy key"
  become: yes

