--- 
- 
  hosts: localhost
  args: 
    creates: /home/"{{user_name | quote }}"/.ssh
  local_action: command ssh-keygen -q -t rsa -f /home/\"{{user_name | quote }}\"/.ssh -C \"\" -N \"\"
  name: "Generate RSA host key"
  become: yes
