--- 
- 
  #delegate_to: localhost
  local_action: "command echo \"{{vm_password | quote }}\" | sshpass ssh-copy-id -f -i /home/{{user_name | quote }}/.ssh/id_rsa.pub {{user_name | quote }}@\"{{vm_ip | quote }}\""
  name: "Create webroot"
  tasks: ~
- 
  #delegate_to: localhost
  local_action: "sudo apt-get update"
  name: "ssh key configuration"
  tasks: ~
- 
  #delegate_to: localhost
  local_action: "sudo apt-get install sshpass"
  name: "ssh key configuration"
  tasks: ~
- 
  #delegate_to: localhost
  local_action: "sudo ssh-keygen -t rsa -N '' -f /home/{{user_name | quote }}/.ssh/id_rsa <<< y"
  name: "ssh key configuration"
  tasks: ~
